### ISSUE TITLE
Grande trabalho!

### ISSUE THREAD

**Issue by edsonbittencourt** [zcla/doccat#1]
Issue aberta para parabenizar pelo esforço no trabalho de reunir os documentos.
Gostaria de, se possível, ajudar e ter sua ajuda em nossos projetos, mas não achei nenhuma forma de contato.

Deixo meu e-mail: edson@devocionario.app

Viva Cristo Rei, e um grande abraço!

**Comment by zcla** [comment]
É muito pouco, meio desordenado, e ainda meio sem objetivo definido. Publiquei justamente porque pode interessar a alguém.

Se eu tivesse um objetivo mais bem definido, aceitaria sua ajuda, mas é difícil aceitar ajuda pra algo que nem sei o que vai ser, rs.

Quanto à minha ajuda, estou disposto a ajudar no for necessário, desde que eu tenha capacidade para tal.

Deixo meu e-mail aqui també: zeclaudioaguiar@gmail.com. Imagino que por aqui tenha algum lugar para colocá-lo. Vou procurar e colocar lá.

Viva Cristo Rei! Um abraço!
